---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  ansible_verbose: true
  ansible_verbosity: 3
  hosts: all
  require_chef_for_busser: false
  require_ruby_for_busser: true
  require_ansible_omnibus: true
  idempotency_test: true
  extra_vars: []
  ansible_version: 2.1

verifier:
  ruby_bindir: '/usr/bin'

platforms:
  - name: trusty64
    driver_plugin: vagrant
    driver_config:
      box: ubuntu/trusty64
      box_url: https://atlas.hashicorp.com/ubuntu/trusty64
      customize:
        memory: 512

suites:
  - name: default
    attributes:
      extra_vars:
        xymon_servers: [ "10.0.15.10" ]
