---
- name: Ensure net tools package is present
  apt: name=net-tools state=present
  tags: [ 'package', 'net-tools' ]

- name: Ensure xymon-client package is present
  apt: name={{ xymon_pkg_name }} state={{ xymon_pkg_state }}
  tags: [ 'package', 'xymon-client' ]

- name: Deploy the xymon-client configuration
  template: src=xymon-client.j2 dest=/etc/default/xymon-client
  tags: [ 'configuration', 'xymon-client' ]
  notify: restart xymon

- name: Ensure xymon-client service is enabled
  service: name={{ xymon_service_name }} state={{ xymon_service_state }} enabled={{ xymon_service_enabled }}
  tags: [ 'service', 'xymon-client' ]
